In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import metrics
import numpy as np
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

In [55]:
# had lots of messed up data in the train dataset! ended up using excel to find and delete the errors rather than code.
test= pd.read_excel(r"C:\Users\latri\Desktop\Pucketts Projects\Datas\ML drugstest.xlsx")
train= pd.read_excel(r"C:\Users\latri\Desktop\Pucketts Projects\Datas\ML drugstrain.xlsx")

In [71]:
test.shape


(53766, 7)

In [72]:
test.head(2)

X     drugName                     condition  \
0  163740  Mirtazapine                    Depression   
1  206473   Mesalamine  Crohn's Disease, Maintenance   

                                              review  rating  \
0  "I&#039;ve tried a few antidepressants over th...      10   
1  "My son has Crohn&#039;s disease and has done ...       8   

                date  usefulCount  
0  February 28, 2012           22  
1       May 17, 2009           17

In [70]:
train.shape


(161293, 7)

In [73]:
train.head(2)

X    drugName                     condition  \
0  206461   Valsartan  Left Ventricular Dysfunction   
1   95260  Guanfacine                          ADHD   

                                              review  rating            date  \
0  "It has no side effect, I take it in combinati...     9.0    May 20, 2012   
1  "My son is halfway through his fourth week of ...     8.0  April 27, 2010   

   usefulCount  
0         27.0  
1        192.0

In [56]:
test.info()
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53766 entries, 0 to 53765
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   X            53766 non-null  int64 
 1   drugName     53766 non-null  object
 2   condition    53471 non-null  object
 3   review       53766 non-null  object
 4   rating       53766 non-null  int64 
 5   date         53766 non-null  object
 6   usefulCount  53766 non-null  int64 
dtypes: int64(3), object(4)
memory usage: 2.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161293 entries, 0 to 161292
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   X            161293 non-null  int64  
 1   drugName     161293 non-null  object 
 2   condition    160325 non-null  object 
 3   review       161224 non-null  object 
 4   rating       161224 non-null  float64
 5   date         161224 non-null  object 
 6   usefulCount  1

In [92]:
drugs = pd.concat([test, train])
drugs= drugs.dropna(inplace=False)

In [86]:
drugs.head(2)

X     drugName                     condition  \
0  163740  Mirtazapine                    Depression   
1  206473   Mesalamine  Crohn's Disease, Maintenance   

                                              review  rating  \
0  "I&#039;ve tried a few antidepressants over th...    10.0   
1  "My son has Crohn&#039;s disease and has done ...     8.0   

                date  usefulCount  
0  February 28, 2012         22.0  
1       May 17, 2009         17.0

In [87]:
drugs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 215059 entries, 0 to 161292
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   X            215059 non-null  int64  
 1   drugName     215059 non-null  object 
 2   condition    213796 non-null  object 
 3   review       214990 non-null  object 
 4   rating       214990 non-null  float64
 5   date         214990 non-null  object 
 6   usefulCount  214990 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB


In [83]:
drugs.shape


(215059, 7)

In [85]:
drugs.drugName.unique()

array(['Mirtazapine', 'Mesalamine', 'Bactrim', ..., 'Mavik', 'Aldomet',
       'Grifulvin V'], dtype=object)

# now to start the real work

In [93]:
X= drugs[['rating','usefulCount']]
y= drugs['drugName']
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = .4)

In [94]:
Dtree = DecisionTreeClassifier()
Dtree.fit(x_train, y_train)
pred= Dtree.predict(x_test)
print(confusion_matrix(y_test, pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [96]:
print(classification_report(y_test, pred))

c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and 

                                                                                                  precision    recall  f1-score   support

                                                                                      A / B Otic       0.00      0.00      0.00         1
                                                            Abacavir / dolutegravir / lamivudine       0.00      0.00      0.00        30
                                                                           Abacavir / lamivudine       0.00      0.00      0.00         3
                                                                                       Abatacept       0.00      0.00      0.00        13
                                                                                         Abilify       0.00      0.01      0.00       236
                                                                                Abilify Discmelt       0.00      0.00      0.00         1
                                 

c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [95]:
forest = RandomForestClassifier(n_estimators=75)
forest.fit(x_train, y_train)
forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and 

                                                                                                  precision    recall  f1-score   support

                                                                                      A / B Otic       0.00      0.00      0.00         1
                                                            Abacavir / dolutegravir / lamivudine       0.00      0.00      0.00        30
                                                                           Abacavir / lamivudine       0.00      0.00      0.00         3
                                                                                       Abatacept       0.00      0.00      0.00        13
                                                                                         Abilify       0.00      0.00      0.00       236
                                                                                Abilify Discmelt       0.00      0.00      0.00         1
                                 

c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Python3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
